import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import Footer from "./components/footer";
import AOSInit from "./components/AOSInit";
import 'aos/dist/aos.css';
import BackToTop from "./components/backToTop";

const barlow = Barlow({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: "--font-barlow",
  display: 'swap',
})

export const metadata: Metadata = {
  title: "wgtecsolutions",
  description: "Generated by Syed Saud Ali",
  icons: {
    icon: "/images/Logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body id="top" className={`${barlow.className} bg-black`}>
        <Navbar />
        <AOSInit />
        {children}
        <BackToTop />
        <Footer />
      </body>
    </html>
  );
}